"""create initial tables

Revision ID: 0a2f359bdca6
Revises: 
Create Date: 2026-09-20 11:20:20.791893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2f359bdca6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', name='meal_type'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'staff', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_slot_id', sa.Integer(), nullable=False),
    sa.Column('menu_date', sa.Date(), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_slot_id'], ['meal_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_slot_id', 'menu_date', name='uq_menu_meal_slot_date')
    )
    op.create_index(op.f('ix_menus_menu_date'), 'menus', ['menu_date'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('hostel_name', sa.String(length=100), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_feedback_rating_range'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_student_id'), 'feedback', ['student_id'], unique=False)
    op.create_table('meal_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('meal_slot_id', sa.Integer(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scanned_by', sa.Integer(), nullable=True),
    sa.Column('entry_method', sa.Enum('qr', 'manual', name='entry_method'), nullable=False),
    sa.ForeignKeyConstraint(['meal_slot_id'], ['meal_slots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'meal_slot_id', 'meal_date', name='uq_student_meal_slot_date')
    )
    op.create_index(op.f('ix_meal_attendance_meal_date'), 'meal_attendance', ['meal_date'], unique=False)
    op.create_index(op.f('ix_meal_attendance_meal_slot_id'), 'meal_attendance', ['meal_slot_id'], unique=False)
    op.create_index(op.f('ix_meal_attendance_student_id'), 'meal_attendance', ['student_id'], unique=False)
    op.create_table('qr_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('meal_slot_id', sa.Integer(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_slot_id'], ['meal_slots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_tokens_meal_date'), 'qr_tokens', ['meal_date'], unique=False)
    op.create_index(op.f('ix_qr_tokens_meal_slot_id'), 'qr_tokens', ['meal_slot_id'], unique=False)
    op.create_index(op.f('ix_qr_tokens_student_id'), 'qr_tokens', ['student_id'], unique=False)
    op.create_index(op.f('ix_qr_tokens_token_hash'), 'qr_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_tokens_token_hash'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_student_id'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_meal_slot_id'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_meal_date'), table_name='qr_tokens')
    op.drop_table('qr_tokens')
    op.drop_index(op.f('ix_meal_attendance_student_id'), table_name='meal_attendance')
    op.drop_index(op.f('ix_meal_attendance_meal_slot_id'), table_name='meal_attendance')
    op.drop_index(op.f('ix_meal_attendance_meal_date'), table_name='meal_attendance')
    op.drop_table('meal_attendance')
    op.drop_index(op.f('ix_feedback_student_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_menus_menu_date'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('meal_slots')
    # ### end Alembic commands ###
