"""add reset passweord

Revision ID: 3ccbca7f6ef1
Revises: e5dee2d4c0e1
Create Date: 2026-09-26 11:12:58.878254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ccbca7f6ef1'
down_revision: Union[str, Sequence[str], None] = 'e5dee2d4c0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
