"""remove roll number and hostel name from students

Revision ID: 82802357a60f
Revises: 7f852d57328a
Create Date: 2026-10-01 20:31:42.736349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82802357a60f'
down_revision: Union[str, Sequence[str], None] = '7f852d57328a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_column('students', 'hostel_name')
    op.drop_column('students', 'roll_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('roll_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('hostel_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    # ### end Alembic commands ###
