"""add weekly menus

Revision ID: e5dee2d4c0e1
Revises: 0a2f359bdca6
Create Date: 2026-09-21 23:48:01.648893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5dee2d4c0e1'
down_revision: Union[str, Sequence[str], None] = '0a2f359bdca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('day_of_week', sa.SmallInteger(), nullable=False))
    op.add_column('menus', sa.Column('menu_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('menus', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('menus', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_menus_menu_date'), table_name='menus')
    op.drop_constraint(op.f('uq_menu_meal_slot_date'), 'menus', type_='unique')
    op.create_index(op.f('ix_menus_day_of_week'), 'menus', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_index(op.f('ix_menus_meal_slot_id'), 'menus', ['meal_slot_id'], unique=False)
    op.create_unique_constraint('uq_menu_day_meal_slot', 'menus', ['day_of_week', 'meal_slot_id'])
    op.drop_column('menus', 'items')
    op.drop_column('menus', 'menu_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('menu_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('menus', sa.Column('items', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_menu_day_meal_slot', 'menus', type_='unique')
    op.drop_index(op.f('ix_menus_meal_slot_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_day_of_week'), table_name='menus')
    op.create_unique_constraint(op.f('uq_menu_meal_slot_date'), 'menus', ['meal_slot_id', 'menu_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_menus_menu_date'), 'menus', ['menu_date'], unique=False)
    op.drop_column('menus', 'updated_at')
    op.drop_column('menus', 'is_active')
    op.drop_column('menus', 'menu_items')
    op.drop_column('menus', 'day_of_week')
    # ### end Alembic commands ###
